# Generated by Django 3.0.2 on 2020-02-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('exposure', models.CharField(choices=[('dark', 'Dark'), ('shade', 'Shade'), ('partsun', 'Part sun'), ('sunny', 'Sunny')], default='', max_length=10, verbose_name='Sun exposure')),
                ('temperature', models.CharField(choices=[('cold', 'Cold'), ('medium', 'Medium'), ('warm', 'Warm')], default='', max_length=10, verbose_name='Temperature')),
                ('humidity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10, verbose_name='Humidity')),
                ('draft', models.BooleanField(blank=True, default=False, verbose_name='Draft')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('watering_interval', models.PositiveIntegerField(help_text='In days', verbose_name='Watering interval')),
                ('fertilizing_interval', models.PositiveIntegerField(help_text='In days', verbose_name='Fertilizing interval')),
                ('required_exposure', models.CharField(choices=[('dark', 'Dark'), ('shade', 'Shade'), ('partsun', 'Part sun'), ('sunny', 'Sunny')], max_length=10, verbose_name='Sun exposure')),
                ('required_temperature', models.CharField(choices=[('cold', 'Cold'), ('medium', 'Medium'), ('warm', 'Warm')], max_length=10, verbose_name='Sun exposure')),
                ('required_humidity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Sun exposure')),
                ('blooming', models.BooleanField(blank=True, default=False, verbose_name='Blooming')),
                ('difficulty', models.PositiveIntegerField(default=1, verbose_name='Cultivation difficulty level')),
                ('last_watered', models.DateField(blank=True, default=None, null=True, verbose_name='Last watering date')),
                ('last_fertilized', models.DateField(blank=True, default=None, null=True, verbose_name='Last fertilizing date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.Category', verbose_name="Plant's category")),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.Room', verbose_name='Room')),
            ],
        ),
    ]
