# Generated by Django 3.0.3 on 2020-02-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20200210_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
